apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com
        revision: HEAD
        files:
          - path: "apps/*/config.json"
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ if hasKey . "syncWave" }}{{ .syncWave }}{{ else }}10{{ end }}'
    spec:
      project: default
      source:
        repoURL: '{{.repoURL}}'
        targetRevision: '{{.targetRevision}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          
  templatePatch: |
    spec:
      source:
        {{- if eq .type "helm" }}
        chart: '{{.chart}}'
        helm:
          releaseName: '{{.path.basename}}'
          valueFiles:
            - 'values.yaml'
        {{- else }}
        path: '{{.path}}'
        {{- end }}

