apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: 'https://github.com/winterlyembrace/itk-gitops-config.git'
        revision: HEAD
        files:
          - path: "apps/*/config.json"
  template:
    metadata:
      name: '{{.path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{ if hasKey . "syncWave" }}{{ .syncWave }}{{ else }}10{{ end }}'
    spec:
      project: default
      sources:
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          
  templatePatch: |
    spec:
      sources:
        {{- if eq .type "helm" }}
      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        helm:
          releaseName: '{{.path.basename}}'
          valueFiles:
            - $customvalues/apps/{{.path.basename}}/values.yaml
      - repoURL: 'https://github.com/winterlyembrace/itk-gitops-config.git'
        ref: customvalues
        {{- else }}
        path: '{{.path.path}}'
      - repoURL: '{{.repoURL}}'
        chart: '{{.chart}}'
        targetRevision: '{{.targetRevision}}'
        directory:
          exclude: 'config.json'
        {{- end }}

