apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca
  namespace: cert-manager
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFEjCCAvqgAwIBAgIUOW3NrXl7CbTEcTmXA4n1Ng7R9/8wDQYJKoZIhvcNAQEL
    BQAwdzELMAkGA1UEBhMCUlUxFDASBgNVBAgMC1ZsYWRpdm9zdG9rMRQwEgYDVQQH
    DAtWbGFkaXZvc3RvazERMA8GA1UECgwIRWdvckNvcnAxCzAJBgNVBAsMAklUMRww
    GgYDVQQDDBNNeSBJbnRlcm5hbCBSb290IENBMB4XDTI2MDYwMjE0NDQxNloXDTI4
    MDYwMTE0NDQxNloweDELMAkGA1UEBhMCUlUxFDASBgNVBAgMC1ZsYWRpdm9zdG9r
    MRQwEgYDVQQHDAtWbGFkaXZvc3RvazERMA8GA1UECgwIRWdvckNvcnAxETAPBgNV
    BAsMCFNlY3VyaXR5MRcwFQYDVQQDDA52YXVsdC5pbnRlcm5hbDCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBALh4dfJCxbOhFvS5snA+k1p1xlD+AzBJGz+t
    guSzGqt5125bLnKHECrfigh2XmwbWsrYhTxnInuJRA0TmO4Y+PEIbHDDtWbXE/9c
    8meHKSijqeTAtkbPZFGNZLH7QB/cbqu/HUgUKz2De8zbJU3w46e6Xdb8gARLwK4e
    CE1fTs7TEeUDyt4mElzDXuo3p9pEIziWPQ8UlXwYNXIgI+vfmOPLI2k6S30Wo6ey
    SP7aOGijYVBaqxU9TxxS59ChrLJ0bO/6LzJNuIagy4gaewJSJGdLo9rgJSo3GMuY
    0tVW7uBokKdB9wIXEuz+2WqtVWt8wBJRumvRS2oDX+D3qQL4Tg8CAwEAAaOBlDCB
    kTAfBgNVHSMEGDAWgBRmuYA/fCV4SafDJhpJFDOE6pUhwDAJBgNVHRMEAjAAMAsG
    A1UdDwQEAwIE8DA3BgNVHREEMDAuhwR/AAABgglsb2NhbGhvc3SHBAqBABKCFXZh
    dWx0Lm1hdHl1a2hpbi5sb2NhbDAdBgNVHQ4EFgQUdMr82CvivFCRN18hMy7jSdK2
    bNkwDQYJKoZIhvcNAQELBQADggIBACJY96ckm2LSvFKHocK81Iy/SkTtjT5CZUva
    nU4wjNTIWotWuwBrxlzYTkdnWuhHzJkir7FtJzBinXFOApIybymdcXzb/By+NIo+
    o8OoTXgJzS7eEa9wpFEIF7AReQO3cqX1vyfovtnkhV4pgvziorJmb7VJ9oZFtPPr
    SQOQO4Ei86btrMXXyu9WgnMCKf3LTHqRTkzgRPOBl2EEw3NMLYMSysGDcxj3KnRc
    DVZ5oIdpGsYAi2sYR8XnfrQYD1LQz4+4Lj3zdSPc18KXlA5nfMVgl8b1xeZq9c6D
    LuFqeKTGnu6vDkaxhsRoByZRop10MOwB3u7zRAE+aIWrOaAmOif++gYJfN7FXpIr
    wK2wZ2W0+scBXIP6bP51kVBFj6MNH8iVzG5jT4vap/gutZbo9WIKW428V3UTE4YM
    IWI4mbH9+ZulRmM30RRTOv1AXqcWbPVItUktYVu22Dze8SCSJ9cF7f0WfvD7L/lW
    Q8+DIwarO29u6gQ0QT3L//oDsD62/k2Xc6fcbyUX5P5gr+kx9+HyHe3zRRu3ON41
    3JPcGEHsiyoi/NWeB4BgL2GKDBBmNSTLgeP8JKxr6T+NffFQ0saHsPcCkrB/KKsV
    MdtRbx43cKHRBecCIm8+bWss0hZb4ue/DLERCdd2cpbiN2HGHjnHE2CkJJJ9H5UU
    e/xYeD2R
    -----END CERTIFICATE-----
