{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
{{- end }}
