deployment:
  kind: Deployment
  replicas: 1  
  podAntiAffinity:  
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
                - traefik
        topologyKey: "kubernetes.io/hostname"

service:
  enabled: true
  type: LoadBalancer

ports:
  web:
    exposedPort: 80
  
  websecure:
    exposedPort: 443

logs:
  general:
    level: INFO                     # Change to WARN or ERROR to save disk space if preferred
    format: json                    # JSON format is easier for Loki / Promtail to parse
  access:
    enabled: true                   # Records every single incoming request
    format: json

metrics:
  prometheus:
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true

