apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-kubernetes-cluster-store
spec:
  provider:
    vault:
      server: "https://10.129.0.39:8200"
      skipTLSVerify: true
      path: "secret"
      version: "v2"
      tls:
        insecureSkipVerify: true
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "argocd-eso-role"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"

