apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: yc-vault-token-generator
spec:
  selector:
    yandex:
      iam:
        secretRef:
          secretStoreRef:
            name: vault-kubernetes-cluster-store
            kind: ClusterSecretStore
          key: infrastructure/yandex
          property: yc-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: yc-registry-oci-auth
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-kubernetes-cluster-store
    kind: ClusterSecretStore
  target:
    name: yc-registry-oci-auth
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: "{{ \"helm\" | b64enc }}"
        enableOCI: "{{ \"true\" | b64enc }}"
        url: "{{ \"cr.yandex\" | b64enc }}"
        username: "{{ \"iam\" | b64enc }}"
        password: "{{ .token | b64enc }}"
        forceHttpBasicAuth: "{{ \"true\" | b64enc }}"
  dataFrom:
    - generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: ClusterGenerator
        name: yc-vault-token-generator

