---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: vault-static-secret-v1
  namespace: vault-secrets-operator
spec:
  vaultAuthRef: vault-auth
  mount: kvv1
  type: kv-v1
  path: grafana/config
  refreshAfter: 60s
  destination:
    create: true
    name: grafana-credentials

