apiVersion: v1
kind: Secret
metadata:
  name: vault-token-reviewer-secret
  namespace: vault-secrets-operator
  annotations:
    kubernetes.io/service-account.name: "vault-token-reviewer"
type: kubernetes.io/service-account-token

